project:
  type: website
  output-dir: docs

website:
  title: "NG'ARA"
  favicon: ngara.png
  site-url: https://lugoga.github.io/semba-quarto/
  description: "Coding for all for better today and tommorow"
  
  navbar:
      right:
        - text: Home
          href: index.qmd
        - text: Blog
          href: blog.qmd 
        - icon: github
          href: https://github.com/lugoga
        - icon: twitter
          href: https://twitter.com/semba2020
        - icon: youtube
          href: https://www.youtube.com/channel/UC9uZ1KPyo7zIzI4BnUtHPfA
  #########################
  # You can ignore this part in the first step
        - icon: rss
          href: blog.xml
        - text: Apps & Links
          menu: 
            - text: Semba-blog Analysis
              href: https://semba.netlify.app/
            - text: Semba Data Analysis
              href: https://semba-blog.netlify.app/
            - text: Kwala commercial CIty
              href: https://semba.shinyapps.io/kwala/
            - text: Marine Hub
              href: https://semba.shinyapps.io/coastal_dashboard/
            - text: Environmental Master Plan
              href: https://nemp.shinyapps.io/nemp/
            - text: Hydrographic Data Hub
              href: https://semba.shinyapps.io/OceanWebApp/
            - text: Potential Fishing Zones
              href: https://semba.shinyapps.io/marineTz/
            - text: Marine Spatial Planning
              href: https://lugoga.github.io/msp/
            - text: R Weekly
              href: https://rweekly.org/
            - text: R Bloggers
              href: https://www.r-bloggers.com/
        - text: Archive
          href: archive.qmd
  google-analytics: "14521548"
  # cookie-consent: 
  #     type: express
  #     style: headline
  #     palette: dark
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@rappa753"
comments:
  giscus:
    repo: lugoga/semba-quarto
  
# filters:
#   - code-filename
######################### 

format:
  html:
    theme: solar

 

