{
  "hash": "05836bb065f8a74adf456153e42c81bc",
  "result": {
    "markdown": "---\ntitle: \"Inferential statistics in R:ttest\"\nauthor: \n  - name: Masumbuko Semba\n    url: https://semba.netlify.app\n    orcid: 0000-0002-5002-9747\n    affiliation: Nelson Mandela African Institution of Science and Technology\n    affiliation-url: https://semba.netlify.app/ \ndate: \"2023-02-15\"\ncategories: [Analysis, Visualization]\n# image: \"family.jpg\"\ndraft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!\nbibliography: ../blog.bib\nexecute: \n  warning: false\n---\n\n\n\nA formal statistical test called a hypothesis test is used to confirm or disprove a statistical hypothesis. The following R hypothesis tests are demonstrated in this course.\n\n-   *T-test with one sample*\n-   *T-Test of two samples*\n-   *T-test for paired samples*\n\nEach type of test can be run using the R function `t.test()`.The function comes with the following arguments;\n\n```r\nt.test(x, y = NULL, \n       alternative = c(\"two-sided\", \"less\", \"greater\"),\n       mu = 0, paired =  FALSE, var.equal = FALSE, conf.level = 0.95, ...)\n```\n\nwhere: \n  $x$ and $y$ are the vectors of data elements\n  $alternative$: the stated alternative hypothesis\n  $mu$: the true value of the mean\n  $paired$: whether or not to run a paired test\n  $var.equal$: whether to assume that the vaarinaces between the values in the vector are equal\n  $con.level$: The confidence level to use\n  \nBefore we proceed, we need functions from various packages and accessing these functions when needed may render this task tedious. Therefore, lets load the packages in advance. These packages include **tidyverse** [@tidyverse], **patchwork**[@patchwork] and **magrittr**[@magrittr]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrequire(tidyverse)\nrequire(patchwork)\nrequire(magrittr)\n```\n:::\n\n\n\n## One sample t-test\n\nOne sample t-test is widely used in statistical analysis to determine whether the population's mean is equal to given mean value. The given mean value can be the sample mean for instance. A `t.test` function in R is used to test one sample parametric test. Let's consider a situation where we want to determine whether the total length of Nile perch collected during a survey conducted in December 2022 is not equal to a long term mean length of 61cm. Let's generate a sample by creating a data frame that contain sample of 350 individual of nile perch. Using a `run_if` function help us simulate weight of nile perch once given the minimum and maximum values. The code for simulating the total length is highlighted in the code chunk below;\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample = tibble::tibble(\n  id = 1:350,\n  tl = runif(n = 350, min = 48, max = 65)\n  )\n\nsample\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 350 x 2\n      id    tl\n   <int> <dbl>\n 1     1  57.8\n 2     2  51.5\n 3     3  56.3\n 4     4  63.0\n 5     5  51.6\n 6     6  53.6\n 7     7  52.5\n 8     8  61.4\n 9     9  58.8\n10    10  62.8\n# ... with 340 more rows\n```\n:::\n:::\n\n\nLet's use a histogram to check the distribution of the data and add a vertical line of the population mean to identify whether the data is leading away is around the population\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample %>% \n  ggplot(aes(x = tl)) +\n  geom_histogram(bins = 30, color = \"ivory\", fill = \"cyan4\")+\n  geom_vline(xintercept = 61, linetype = 2, color = \"red\")+\n  scale_x_continuous(name = \"Total length (cm.)\", breaks = seq(40,80,4)) +\n  scale_y_continuous(name = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-pdf/fig-hist-1.pdf){#fig-hist fig-pos='H'}\n:::\n:::\n\n\nNow we notice that the position of the population mean of the sample dataset, we can not test to determine whether the sample mean total length is lower than the sample mean\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample %$%\n  t.test(x = tl, mu = 61, alternative = \"less\") \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  tl\nt = -17.298, df = 349, p-value < 2.2e-16\nalternative hypothesis: true mean is less than 61\n95 percent confidence interval:\n     -Inf 56.88185\nsample estimates:\nmean of x \n 56.44785 \n```\n:::\n:::\n\n\nThe one sample t-test determine the whether the sample mean total length of nile perch was less than the long-term mean length suggest that the sample total length (56.68cm) was less than the population mean (61cm) and the difference was statistically significant  (t(349) = -18.19, p < 0.001). Lets try change the alternative to `greater`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample %$%\n  t.test(x = tl, mu = 61, alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  tl\nt = -17.298, df = 349, p-value = 1\nalternative hypothesis: true mean is greater than 61\n95 percent confidence interval:\n 56.01384      Inf\nsample estimates:\nmean of x \n 56.44785 \n```\n:::\n:::\n\nNotice that the test is not statistically significant (t(349) = 18.91, p = 1) because the population mean (61cm) is greater than the sample mean (56.68).\n\n\n## Two Sample t-test\n\nA two sample t-test is used to determine whether the means of two independent samples are equal. Lets consider that two independent survey to measure the stock of nile perch was conducted in two independent period. The first survey was conducted in June 2001 and the subsequency survey was conducted in July 2021. The two survey were conducted during the cool and dry season but with a 20 years time difference. Therefore, we want to determine whether the mean sample of nile perch collected in 2021 is smaller than the those sampled in 2001\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1254)\n\nsample2 = tibble::tibble(\n  id = 1:350,\n  tl21 = rnorm(n = 350,mean = 52, sd = 18),\n  tl01 = rnorm(n = 350, mean = 61, sd = 20)\n  )\n\nsample2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 350 x 3\n      id  tl21  tl01\n   <int> <dbl> <dbl>\n 1     1 41.7   54.4\n 2     2 68.4   52.2\n 3     3 47.1   69.1\n 4     4 38.7   43.2\n 5     5  3.41  46.9\n 6     6 42.6   64.3\n 7     7 67.3   70.4\n 8     8 65.7   72.9\n 9     9 26.3   25.0\n10    10 56.2   64.5\n# ... with 340 more rows\n```\n:::\n:::\n\n\nOnce we have created a dataframe with values for the two sampling survey, it's a good practice to visualize the value to see the patterns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample2 %>% \n  pivot_longer(cols = tl21:tl01) %>% \n  ggplot(aes(x = value, fill = name))+\n  geom_density(position = \"identity\", alpha = .4)+\n  scale_fill_brewer(name =\"Surveys\" ,palette = \"Set2\", label = c(\"2001\", \"2021\"))+\n  scale_x_continuous(name = \"Total length (cm)\", breaks = seq(20,150,20))+\n  scale_y_continuous(name = \"Density\")+\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nWe notice from a figure above a slight difference in the density shape with the median value for 2001 far east from the 2021, suggesting the size of 2001 is relatively higher than 2001. Let's perform two sample t-test to determine whether that difference is significant;\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample2 %$%\n  t.test(x = tl21, y = tl01, alternative = \"less\") \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  tl21 and tl01\nt = -6.4619, df = 690.02, p-value = 9.771e-11\nalternative hypothesis: true difference in means is less than 0\n95 percent confidence interval:\n      -Inf -6.905485\nsample estimates:\nmean of x mean of y \n 51.80015  61.06788 \n```\n:::\n:::\n\n\nThe output display the Welch Two Sample t-test to determine whether the total length of nile perch sampled in 2021 is less than those of 2001. The result suggest that the sample mean in 2021 was 51.8 cm which is less than 61.07 cm of nile perch sampled in 2001. The result suggest that the 2021 nile perch were small in size than those of 2001, and the difference was significant (t(690) = 6.46, p < 0.01).\n\n\n## Paired sample t-test\n\nThis test is normally used to determine whether the values in paired dataset have different mean. For instance, the weight in nile perch measured after captured and kept in cage for three months and measured again. Therefore, the nile perch individuals were measured before taken to cage and then measured after three months. This means we have measurement before and after. Let's create a dataframe and simulate before and after total length of nile perch.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1254)\n\nsample3 = tibble::tibble(\n  id = 1:50,\n  before = rnorm(n = 50,mean = 52, sd = 12),\n  after = before + rnorm(n = 50) %>% abs()\n  )\n\nsample3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 50 x 3\n      id before after\n   <int>  <dbl> <dbl>\n 1     1   45.1  46.2\n 2     2   62.9  64.7\n 3     3   48.7  49.3\n 4     4   43.2  43.6\n 5     5   19.6  20.4\n 6     6   45.7  46.1\n 7     7   62.2  63.2\n 8     8   61.1  62.5\n 9     9   34.9  35.2\n10    10   54.8  56.0\n# ... with 40 more rows\n```\n:::\n:::\n\n\nThen we perform paired sample t-test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample3 %$%\n  t.test(x = before, y = after, paired = TRUE) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  before and after\nt = -11.171, df = 49, p-value = 4.484e-15\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -0.9512640 -0.6612062\nsample estimates:\nmean of the differences \n             -0.8062351 \n```\n:::\n:::\n\n\nSince the p < 0.05, we reject the null hypothesis that the mean total length before and after is significant. Therefore, fattening nile perch in cage for three months increased the total length and that increase is significant (t(49) = -11.17, p < 0.001)\n\n\n## Cited Materials\n",
    "supporting": [
      "index_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}